hotelsystem/force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brest</fullName>
            </value>
            <value>
                <fullName>Minsk</fullName>
            </value>
            <value>
                <fullName>Vitebsk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hotelsystem/force-app/main/default/objects/Hotel__c/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <label>ImageURL</label>
    <type>Url</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hotelsystem/force-app/main/default/objects/Reservation__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <label>Check In</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <label>Check Out</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.Hotel__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Hotel__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation__c/fields/Total_Reservation_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Reservation_Cost__c</fullName>
    <formula>(Check_Out__c - Check_In__c) * Room__r.Price_per_Day__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Reservation Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation_Service__c/Reservation_Service__c.object-meta.xml
<CustomObject>
    <label>Reservation Service</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reservation Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hotelsystem/force-app/main/default/objects/Reservation_Service__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservation Services</relationshipLabel>
    <relationshipName>Reservation_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Reservation_Service__c/fields/Service_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Service_Hotel__c</fullName>
    <label>Service Hotel</label>
    <referenceTo>Service_Hotel__c</referenceTo>
    <relationshipLabel>Reservation Services</relationshipLabel>
    <relationshipName>Reservation_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hotelsystem/force-app/main/default/objects/Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hotelsystem/force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Room__c/fields/Price_per_Day__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Day__c</fullName>
    <label>Price per Day</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hotelsystem/force-app/main/default/objects/Service_Hotel__c/Service_Hotel__c.object-meta.xml
<CustomObject>
    <label>Service Hotel</label>
    <nameField>
        <label>Service Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Hotel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hotelsystem/force-app/main/default/objects/Service_Hotel__c/fields/Price_per_Day__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Day__c</fullName>
    <label>Price per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

hotelsystem/force-app/main/default/classes/HotelCmpController.cls
public with sharing class HotelCmpController {
    
    @AuraEnabled
    public static Map<String, String> getCity(){
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Hotel__c.City__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static List<Hotel__c> getHotelListA(string searchcity) {
        List<Hotel__c> listHotel;
        listHotel = [SELECT Id, Name, City__c, Street__c, ImageURL__c, Phone__c, Description__c FROM Hotel__c WHERE City__c =: searchcity ORDER BY Name ASC];
        return listHotel;
    }
    
    @AuraEnabled
    public static Map<String, String> getCapacity(){
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Room__c.Capacity__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static List<Room__c> getRoomListA(string searchcapacity, string searchhotel, Date startDate, Date endDate) {
        List<Reservation__c> reservations = [
            SELECT room__r.id FROM Reservation__c 
            WHERE (Check_In__c < :endDAte and Check_In__c >= :startDate) or (Check_Out__c <= :endDAte and Check_Out__c > :startDate)
        ];
        
        List<Id> reserved_rooms = new List<Id>();
        for (Reservation__c reservation: reservations){
            reserved_rooms.add(reservation.room__r.id);
        }
        
        List<Room__c> listRoom = [
            SELECT Id, Name, Price_per_Day__c, Capacity__c FROM Room__c
            WHERE Hotel__r.id = :searchhotel AND Capacity__c = :searchcapacity AND Id NOT IN :reserved_rooms
            ORDER BY Name DESC
        ];
        return listRoom;
    }
    
    @AuraEnabled
    public static List<Service_Hotel__c> getServiceList() {
        List<Service_Hotel__c> listService;
        listService = [SELECT Id, Name, Price_per_Day__c FROM Service_Hotel__c];
        return listService;
    }
    
    @AuraEnabled
    public static Reservation__c saveNewReservation
        (Reservation__c newReservationA, String idHotelA, String idRoomA, List<String> valueSerA, Date startDateA, Date endDateA){
            Date startDate = date.valueOf(startDateA);                                                
            Date endDate = date.valueOf(endDateA);
            newReservationA.RecordTypeId = '0122w000000Y5BpAAK';
            newReservationA.Hotel__c = [SELECT Id FROM Hotel__c WHERE Id =:idHotelA LIMIT 1].Id;
            newReservationA.Room__c = [SELECT Id FROM Room__c WHERE Id =:idRoomA LIMIT 1].Id;
            upsert newReservationA;
            for (String serId: valueSerA)
            {
                Reservation_Service__c rs = new Reservation_Service__c();
                rs.Service_Hotel__c = serId;
                rs.Reservation__c = newReservationA.Id;
                insert rs;
            }        
            return newReservationA = [SELECT Id, Name FROM Reservation__c LIMIT 1];
            /*return newReservationA = [SELECT Id, Name, Check_In__c, Check_Out__c, Total_Reservation_Cost__c, 
                               Hotel__r.Name, Hotel__r.City__c, Hotel__r.Street__c, 
                               Room__r.Name, Room__r.Capacity__c FROM Reservation__c];*/
            
        }  
    
    @AuraEnabled 
    public static void sendMailMethod(String mMail ,String mSubject ,String mbody){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {mMail};
            mail.setToAddresses(toAddresses);
        mail.setSubject(mSubject);
        mail.setPlainTextBody(mbody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
    }
}